# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: '5.0.x'

- task: PowerShell@2
  displayName: 'Install Sql Server tools'
  inputs:
    targetType: 'inline'
    script: |
      Install-Module -Name SqlServer -AllowClobber -Force

- script: dotnet tool install --global dotnet-ef
  displayName: 'Install Entity Framework tools'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build Project ($(buildConfiguration))'

- powershell: |
    Write-Host "DatabaseName: $(DATABASENAME)"
    #& (".\scripts\Database.ps1") -Clean -DatabaseName $(DATABASENAME) -ServerInstance $(SERVERINSTANCE) -ServerUsername $(SERVERUSERNAME) -ServerPassword $(SERVERPASSWORD)
  env:
    DATABASENAME: $(DatabaseName)

#- task: PowerShell@2
#  displayName: 'Build Database'
#  inputs:
#    targetType: 'inline'
#    script: |
#      & (".\scripts\Database.ps1") -Clean -DatabaseName $(DATABASENAME) -ServerInstance $(SERVERINSTANCE) -ServerUsername $(SERVERUSERNAME) -ServerPassword $(SERVERPASSWORD)

#- task: DotNetCoreCLI@2
#  displayName: 'dotnet test'
#  inputs:
#    command: 'test'