// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace ProjectX.Data.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(ProjectXDbContext))]
    internal class ProjectXDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ProjectX.Data.Version.EntityVersion", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .UseIdentityColumn();

                b.Property<int>("Build")
                    .HasColumnType("int");

                b.Property<DateTimeOffset>("CreatedDateTime")
                    .HasColumnType("datetimeoffset");

                b.Property<int>("Major")
                    .HasColumnType("int");

                b.Property<int>("Minor")
                    .HasColumnType("int");

                b.Property<int>("Revision")
                    .HasColumnType("int");

                b.Property<DateTimeOffset>("UpdatedDateTime")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.ToTable("Versions");
            });
#pragma warning restore 612, 618
        }
    }
}